spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clothify
    username: root
    password: 992412712V
  jpa:
    hibernate:
      ddl-auto: create
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true